  Owner      = RECORD
                 Marca       : String[15];
                 RSocial     : String[40];
                 Endereco    : String[40];
                 Numero      : String[10];
                 Complemento : String[15];
                 Bairro      : String[20];
                 Cidade      : String[20];
                 Estado      : String[2];
                 Cep         : String[9];
                 Telefone    : String[15];
                 Cgc         : String[20];
                 Inscricao   : String[20];
                 NBase       : Integer;
                 NoSerie     : String[8];
                 Versao      : String[8];
                 Produto     : String[6];
               END;
